Use spaces instead of tabs to make SHFMT happy
Change-Id: I9c1635ae07dd943b09665f41753a33ffbbbfba73
Signed-off-by: Joakim Roubert <joakimr@axis.com>

diff --git a/vapix-sh/app/vapix_example_sh b/vapix-sh/app/vapix_example_sh
--- a/vapix-sh/app/vapix_example_sh
+++ b/vapix-sh/app/vapix_example_sh
@@ -5,40 +5,40 @@ BASEURL=http://127.0.0.12/axis-cgi
 
 # Get the VAPIX credentials from D-Bus
 CREDENTIALS=$(dbus-send --system \
-	--print-reply \
-	--dest=com.axis.HTTPConf1 \
-	/com/axis/HTTPConf1/VAPIXServiceAccounts1 \
-	com.axis.HTTPConf1.VAPIXServiceAccounts1.GetCredentials \
-	string:"$USERNAME")
+  --print-reply \
+  --dest=com.axis.HTTPConf1 \
+  /com/axis/HTTPConf1/VAPIXServiceAccounts1 \
+  com.axis.HTTPConf1.VAPIXServiceAccounts1.GetCredentials \
+  string:"$USERNAME")
 CREDENTIALS=${CREDENTIALS#*\"}
 CREDENTIALS=${CREDENTIALS%\"*}
 
 # Function that does VAPIX requests
 request() {
-	[ $# -eq 2 ] || {
-		echo "Error: expected 2 parameters but got $#" >&2
-		return 1
-	}
+  [ $# -eq 2 ] || {
+    echo "Error: expected 2 parameters but got $#" >&2
+    return 1
+  }
 
-	response=$(curl -s -u "$CREDENTIALS" -H 'Content-Type: application/json' -d "$1" "$BASEURL/$2")
+  response=$(curl -s -u "$CREDENTIALS" -H 'Content-Type: application/json' -d "$1" "$BASEURL/$2")
 
-	error=$(echo "$response" | jq -r '.error.message // empty')
-	[ -z "$error" ] || {
-		echo "Error: $error" >&2
-		return 1
-	}
-	echo "$response"
+  error=$(echo "$response" | jq -r '.error.message // empty')
+  [ -z "$error" ] || {
+    echo "Error: $error" >&2
+    return 1
+  }
+  echo "$response"
 }
 
 # Function that reads and prints a specific item (second parameter) from a
 # basic device info property list (provided as the first parameter)
 read_property() {
-	[ $# -eq 2 ] || {
-		echo "Error: expected 2 parameters but got $#" >&2
-		return 1
-	}
+  [ $# -eq 2 ] || {
+    echo "Error: expected 2 parameters but got $#" >&2
+    return 1
+  }
 
-	echo "$2: $(echo "$1" | jq -r ".data.propertyList.$2 // empty")"
+  echo "$2: $(echo "$1" | jq -r ".data.propertyList.$2 // empty")"
 }
 
 # Retrieve and print curl version
@@ -55,4 +55,3 @@ DATA=$(request "$REQUEST" basicdeviceinfo.cgi)
 read_property "$DATA" ProdShortName
 read_property "$DATA" Soc
 read_property "$DATA" SocSerialNumber
-
